#!/bin/bash

# When Soong runs this script, $(pwd) is the LineageOS root.
# We must explicitly define the kernel root based on where this script is located,
# and cd into it so all relative EXT_MODULES paths work perfectly.
export KERNEL_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd ${KERNEL_ROOT_DIR}

# Now ANDROID_BUILD_TOP is safely locked to the kernel root as Lineage OS would expect
export ANDROID_BUILD_TOP=${KERNEL_ROOT_DIR}

# OEM Setting
BUILD_TARGET=m55xq_swa_open
export MODEL=$(echo $BUILD_TARGET | cut -d'_' -f1)
export PROJECT_NAME=${MODEL}
export REGION=$(echo $BUILD_TARGET | cut -d'_' -f2)
export CARRIER=$(echo $BUILD_TARGET | cut -d'_' -f3)
export TARGET_BUILD_VARIANT=user

CHIPSET_NAME=x55
export TARGET_PRODUCT=gki
export TARGET_BOARD_PLATFORM=gki

export ANDROID_PRODUCT_OUT=${ANDROID_BUILD_TOP}/out/target/product/${MODEL}
export OUT_DIR=${ANDROID_BUILD_TOP}/out/msm-${CHIPSET_NAME}-${CHIPSET_NAME}-${TARGET_PRODUCT}
export DIST_DIR=${ANDROID_BUILD_TOP}/out/msm-${CHIPSET_NAME}-${CHIPSET_NAME}-${TARGET_PRODUCT}/dist
export MERGE_CONFIG="${ANDROID_BUILD_TOP}/kernel_platform/common/scripts/kconfig/merge_config.sh"

mkdir -p "${DIST_DIR}"

export IS_KBUILD=true
export MODNAME=audio_dlkm

export EXT_MODULES=" \
    ../vendor/qcom/opensource/mmrm-driver \
    ../vendor/qcom/opensource/audio-kernel \
    ../vendor/qcom/opensource/datarmnet/core \
    ../vendor/qcom/opensource/datarmnet-ext/shs \
    ../vendor/qcom/opensource/datarmnet-ext/sch \
    ../vendor/qcom/opensource/datarmnet-ext/perf \
    ../vendor/qcom/opensource/datarmnet-ext/perf_tether \
    ../vendor/qcom/opensource/datarmnet-ext/offload \
    ../vendor/qcom/opensource/datarmnet-ext/aps \
    ../vendor/qcom/opensource/datarmnet-ext/wlan \
    ../vendor/qcom/opensource/wlan/qcacld-3.0 \
    ../vendor/qcom/opensource/camera-kernel \
    ../vendor/qcom/opensource/display-drivers/msm \
    ../vendor/qcom/opensource/video-driver \
    ../vendor/qcom/opensource/eva-kernel \
    ../vendor/qcom/opensource/cvp-kernel \
    ../vendor/qcom/opensource/dataipa/drivers/platform/msm"

export GKI_KERNEL_BUILD_OPTIONS=" \
    SKIP_MRPROPER=1 \
    LTO=thin \
    HERMETIC_TOOLCHAIN=1 \
    KMI_SYMBOL_LIST_STRICT_MODE=0 \
    RECOMPILE_KERNEL=1 \
    ABI_DEFINITION= \
    BUILD_BOOT_IMG=1 \
    SKIP_VENDOR_BOOT=1 \
    MKBOOTIMG_PATH=${ANDROID_BUILD_TOP}/kernel_platform/tools/mkbootimg/mkbootimg.py \
    KERNEL_BINARY=Image \
    BOOT_IMAGE_HEADER_VERSION=4 \
    AVB_SIGN_BOOT_IMG=1 \
    AVB_BOOT_PARTITION_SIZE=100663296 \
    AVB_BOOT_KEY=${ANDROID_BUILD_TOP}/kernel_platform/tools/mkbootimg/tests/data/testkey_rsa2048.pem \
    AVB_BOOT_ALGORITHM=SHA256_RSA2048 \
    AVB_BOOT_PARTITION_NAME=boot \
"

export MKBOOTIMG_EXTRA_ARGS=" \
    --os_version 12.0.0 \
    --os_patch_level 2025-12-00 \
    --pagesize 4096 \
"

# Set a LOCALVERSION before compiling.
export LOCALVERSION="-lineage-kernel-test"

# Cook kernel
env ${GKI_KERNEL_BUILD_OPTIONS} ${ANDROID_BUILD_TOP}/kernel_platform/build/android/prepare_vendor.sh sec ${TARGET_PRODUCT} | tee -a build.log

# ====================================================================
#  The soong handoff (for lineage)
# ====================================================================

if [ -n "$KERNEL_OUT" ] && [ -n "$KERNEL_MODULES_OUT" ]; then
    echo "================================================="
    echo "Lineage OS detected, handing build to soong"
    echo "================================================="
    
    # Make sure Lineage's output directories exist
    mkdir -p ${KERNEL_OUT}
    mkdir -p ${KERNEL_MODULES_OUT}

    # 1. Shove the Image directly into Lineage's obj folder
    cp ${DIST_DIR}/Image ${KERNEL_OUT}/Image
    
    # 2. Shove the Device Tree Blob (dtb)
    if [ -f ${DIST_DIR}/dtb ]; then
        cp ${DIST_DIR}/dtb ${KERNEL_OUT}/dtb
    fi

    # 3. Find EVERY .ko module generated by those EXT_MODULES 
    # and violently force them into the ROM's vendor_boot path
    find ${DIST_DIR} -type f -name "*.ko" -exec cp {} ${KERNEL_MODULES_OUT}/ \;

    echo "Kernel handoff complete! LineageOS will now pack the payload."

else
    echo "================================================="
    echo "STANDALONE BUILD DETECTED (No Soong variables)"
    echo "================================================="
    # Your original manual boot.img copy
    cp ${DIST_DIR}/boot.img ${ANDROID_BUILD_TOP}/boot.img
    echo "boot.img is ready in ${ANDROID_BUILD_TOP}/boot.img"
fi

